version: '3.3'

networks:
  enterprise-beers:

services:
  beer-api:
    image: enterprisebeers.azurecr.io/beer-api:1.0.95
    container_name: beer-api
    volumes:
      - ./demo-3-config.txt:/config/jvm.options
    networks:
      - enterprise-beers

  brewery-api-1:
    image: enterprisebeers.azurecr.io/brewery-api:1.0.95
    container_name: brewery-api-1
    volumes:
      - ./demo-3-config.txt:/config/jvm.options
    networks:
      - enterprise-beers

  brewery-api-2:
    image: enterprisebeers.azurecr.io/brewery-api:1.0.95
    container_name: brewery-api-2
    volumes:
      - ./demo-3-config.txt:/config/jvm.options
    networks:
      - enterprise-beers

  postgresql:
    image: postgres:11.2-alpine
    container_name: postgresql
    ports:
      - 5432:5432
    networks:
      - enterprise-beers
    volumes:
      - ./demo2-pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: kong
      POSTGRES_USER: kong
      POSTGRES_PASSWORD: s3cr3t

  kong-db-migration:
    image: kong:1.0.3-alpine
    container_name: kong-db-migration
    networks:
      - enterprise-beers
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: postgresql
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: s3cr3t
    command: /bin/sh -c "kong migrations bootstrap && kong migrations --v up"
    depends_on:
      - postgresql

  kong:
    image: kong:1.0.3-alpine
    container_name: kong
    ports:
      - 8000:8000
      - 8001:8001
    networks:
      - enterprise-beers
    restart: always
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: postgresql
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: s3cr3t
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
    depends_on:
      - kong-db-migration





